# Take the user Input and Print the details
name= input("Enter your Name ")
age= input("Enter your Age ")
roll_number= input("Enter your Roll Number ")
phone_number= input("Enter your Phone Number ")
print("User Details")
print("User Name=",name)
print("User Age=",age)
print("User Roll_Number=",roll_number)
print("User Phone Number=",phone_number)